=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Ejemplos/book17.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Author">
        <xs:complexContent>
            <xs:extension base="PersonType" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Ilustrator">
        <xs:complexContent>
            <xs:extension base="PersonType">
                <xs:sequence>
                    <xs:element name="Awards" type="xs:string" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="xs:string" />
                <xs:element name="Author" type="Author" />
                <xs:element name="Ilustrator" type="Ilustrator" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Ejemplos/book17.xml
<?xml version="1.0" encoding="UTF-8"?>
<Book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="book17.xsd">
      <Title>Copia este libro</Title>
      <Author>
            <Name>David Bravo</Name>
      </Author>
      <Ilustrator>
            <Name>Pablo Soto</Name>
            <Awards>15m</Awards>
            <Awards>Sinde</Awards>
      </Ilustrator>
</Book>
