=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Ejemplos/person16.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="Person">
      <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Awards" type="xs:string" minOccurs="0"/>
      </xs:sequence>
</xs:complexType>


<xs:complexType name="PersonExtended">
      <xs:complexContent>
          <xs:extension base="Person">
                <xs:sequence>
                      <xs:element name="Company" type="xs:string"/>
                </xs:sequence>
          </xs:extension>
          </xs:complexContent>
      </xs:complexType>
<!--elemento raíz-->      
  <xs:element name="Book">
      <xs:complexType>
      <xs:sequence>
              <xs:element name="Title" type="xs:string"/>
              <xs:element name="Author" type="Person"/>
              <xs:element name="Illustrator" type="PersonExtended"   minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Ejemplos/person16.xml
<?xml version="1.0" encoding="UTF-8"?>
<Book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="person16.xsd">
          <Title>Copia este libro</Title>
          <Author>
              <Name>David Bravo</Name>
              <Awards>15m</Awards>
          </Author>
          <Illustrator>
                  <Name>Pablo Soto</Name>
                  <Company>Una</Company>
          </Illustrator>
</Book>
