=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ej3-ligafutbol/ligafutbol1.dtd
<!ELEMENT ligafutbol (partido+)>
    <!ELEMENT partido (equipo+)>
        <!ELEMENT equipo (tipo, nombre, goles)>
            <!ELEMENT tipo (#PCDATA)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT goles (#PCDATA)>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ligafutbol/ligafutbol1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligafutbol SYSTEM "./ligafutbol1.dtd">
<ligafutbol>
    <partido>
        <equipo>
            <tipo>Local</tipo>
            <nombre>Nottingham Presa: </nombre>
            <goles>0</goles>
        </equipo>
        <equipo>
            <tipo>Visitante</tipo>
            <nombre>Inter de Mitente: </nombre>
            <goles>1</goles>
        </equipo>
    </partido>
    <partido>
        <equipo>
            <tipo>Local</tipo>
            <nombre>Vodka Juniors: </nombre>
            <goles>3</goles>
        </equipo>
        <equipo>
            <tipo>Visitante</tipo>
            <nombre>Sparta da Risa: </nombre>
            <goles>3</goles>
        </equipo>
    </partido>
    <partido>
        <equipo>
            <tipo>Local</tipo>
            <nombre>Water de MÃºnich: </nombre>
            <goles>4</goles>
        </equipo>
        <equipo>
            <tipo>Visitante</tipo>
            <nombre>Esteaua es del grifo: </nombre>
            <goles>2</goles>
        </equipo>
    </partido>
</ligafutbol>
