=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Practica XML XSD/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoPrecio">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0" />
            <xs:maxInclusive value="999" />
            <xs:totalDigits value="5" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoArticulo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DVD" />
            <xs:enumeration value="Libro" />
            <xs:enumeration value="Varios" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTexto">
        <xs:restriction base="xs:string">
            <xs:minLength value="5" />
            <xs:maxLength value="20" />
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="datos">
        <xs:sequence>
            <xs:element name="nombre" type="tipoTexto" />
            <xs:element name="cif">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{8}\-[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="telefono">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{9}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="factura">
        <xs:complexType>
            <xs:all>
                <xs:element name="datos_emisor">
                    <xs:complexType>
                        <xs:group ref="datos" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_cliente">
                    <xs:complexType>
                        <xs:group ref="datos" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="detalle_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="articulo" maxOccurs="15">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="tipoArticulo" />
                                        <xs:element name="descripcion" type="tipoTexto" />
                                        <xs:element name="cantidad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="0" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="oferta" minOccurs="0" />
                                        <xs:element name="pvp" type="tipoPrecio" />
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="importe" type="tipoPrecio" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="numero" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minExclusive value="0" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="fecha" type="xs:date" use="required" />
            <xs:attribute name="moneda" fixed="â‚¬" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Practica XML XSD/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./factura.xsd" fecha="2021-02-23" numero="19" moneda="â‚¬">
    <datos_emisor>
        <nombre>Libreria aCoslada</nombre>
        <cif>12345678-B</cif>
        <telefono>123456789</telefono>
    </datos_emisor>
    <datos_cliente>
        <nombre>IES Luis Braille</nombre>
        <cif>87654321-A</cif>
        <telefono>987654321</telefono>
    </datos_cliente>
    <detalle_factura importe="85">
        <articulo codigo="AW7" >
            <tipo>Libro</tipo>
            <descripcion>Aplicaciones Web</descripcion>
            <cantidad>2</cantidad>
            <oferta/>
            <pvp>25</pvp>
        </articulo>
        <articulo codigo="LM5" >
            <tipo>Libro</tipo>
            <descripcion>Lenguaje de Marcas</descripcion>
            <cantidad>1</cantidad>
            <pvp>30</pvp>
        </articulo>
    </detalle_factura>
</factura>
