=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Practica XML XSD/registro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="apellidos-y-nombre">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z&#x20;]{1,30}\,[a-zA-Z&#x20;]{1,20}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]{1,15}@[a-z]{1,25}\.[a-z]{2,4}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="conexiones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="conexion" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="fecha" type="xs:date" />
                                    <xs:element name="hora" type="xs:time" />
                                    <xs:element name="segundos">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="0" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="identificador">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(U|E){1}[0-9]{1,5}" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoPersonaAmpliado">
        <xs:complexContent>
            <xs:extension base="tipoPersona">
                <xs:sequence>
                    <xs:element name="departamento">
                        <xs:complexType>
                            <xs:choice>
                                <xs:element name="Administración" />
                                <xs:element name="Informática" />
                                <xs:element name="Marketing" />
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="registros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" type="tipoPersona" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" type="tipoPersonaAmpliado" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/3 Trimestre/Practica XML XSD/registro.xml
<?xml version="1.0" encoding="UTF-8"?>
<registros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./registro.xsd">
    <usuarios>
        <usuario identificador="U123">
            <apellidos-y-nombre>Sanz Tapia, Ana</apellidos-y-nombre>
            <email>asanz@jimail.com</email>
            <conexiones>
                <conexion>
                    <fecha>2014-02-23</fecha>
                    <hora>19:15:40</hora>
                    <segundos>122</segundos>
                </conexion>
                <conexion>
                    <fecha>2014-02-23</fecha>
                    <hora>20:30:22</hora>
                    <segundos>617</segundos>
                </conexion>
                <conexion>
                    <fecha>2014-02-24</fecha>
                    <hora>11:18:31</hora>
                    <segundos>25</segundos>
                </conexion>
            </conexiones>
        </usuario>
        <usuario identificador="U96">
            <apellidos-y-nombre>Ruiz Hierro, Pedro</apellidos-y-nombre>
            <email>pruiz@jotmail.com</email>
            <conexiones>
                <conexion>
                    <fecha>2014-02-25</fecha>
                    <hora>20:33:55</hora>
                    <segundos>390</segundos>
                </conexion>
            </conexiones>
        </usuario>
    </usuarios>
    <empleados>
        <empleado identificador="E4">
            <apellidos-y-nombre>Vera Gil, Marta</apellidos-y-nombre>
            <email>mvera@yajoo.es</email>
            <conexiones></conexiones>
            <departamento>
                <Marketing></Marketing>
            </departamento>
        </empleado>
    </empleados>
</registros>
