=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ligafutbol/ligafutbol3.dtd
<!ELEMENT ligafutbol (partido+)>
    <!ELEMENT partido (equipo+)>
        <!ELEMENT equipo EMPTY>
            <!ATTLIST equipo goles CDATA #REQUIRED>
            <!ATTLIST equipo nombre CDATA #REQUIRED>
            <!ATTLIST equipo tipo (Local|Visitante) #REQUIRED>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ligafutbol/ligafutbol3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligafutbol SYSTEM "./ligafutbol3.dtd">
<ligafutbol>
    <partido>
        <equipo tipo="Local" nombre="Nottingham Presa" goles="0"/>
        <equipo tipo="Visitante" nombre="Inter de Mitente" goles="1"/>
    </partido>
    <partido>
        <equipo tipo="Local" nombre="Vodka Juniors" goles="3"/>
        <equipo tipo="Visitante" nombre="Sparta da Risa" goles="3"/>
    </partido>
    <partido>
        <equipo tipo="Local" nombre="Water de MÃºnich" goles="4"/>
        <equipo tipo="Visitante" nombre="Esteaua es del grifo" goles="2"/>
    </partido>
</ligafutbol>
