=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ej10-empleados.dtd
<!ELEMENT empleados (area+)>
    <!ELEMENT area (empleado+)>
        <!ATTLIST area area (administración|informática|diseño) #REQUIRED>
        <!ELEMENT empleado (apellido, nombre, cargo?, salario?)>
            <!ATTLIST empleado idempleado CDATA #REQUIRED>
            <!ATTLIST empleado fechainicio CDATA #REQUIRED>
            <!ATTLIST empleado fechanacimiento CDATA #REQUIRED>
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT cargo (#PCDATA)>
            <!ELEMENT salario (#PCDATA)>

=== Karlosjp/Clase-DAM/Luis Braille/1 DAM/Lenguaje de Marcas/2 Trimestre/Ejercicios XML-DTD/ej10-empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "./ej10-empleados.dtd">
<empleados>
    <area area="administración">
        <empleado idempleado="1968" fechainicio="05/04/2020" fechanacimiento="28/09/1973">
            <apellido>Burgos</apellido>
            <nombre>Jerónimo</nombre>
            <cargo>Administrativo</cargo>
            <salario>20.000</salario>
        </empleado>
        <empleado idempleado="1674" fechainicio="25/03/2005" fechanacimiento="17/01/1980">
            <apellido>Villegas</apellido>
            <nombre>Estefanía</nombre>
            <cargo>Docente</cargo>
            <salario>30.000</salario>
        </empleado>
        <empleado idempleado="1516" fechainicio="06/03/2010" fechanacimiento="26/06/1975">
            <apellido>Fernández</apellido>
            <nombre>Guillermo</nombre>
            <cargo>Docente</cargo>
            <salario>30.000</salario>
        </empleado>
    </area>
    <area area="diseño">
        <empleado idempleado="1657" fechainicio="06/06/2001" fechanacimiento="19/06/1975">
            <apellido>Carmona</apellido>
            <nombre>José</nombre>
            <cargo>Administrativo</cargo>
            <salario>15.000</salario>
        </empleado>
        <empleado idempleado="1078" fechainicio="19/06/2010" fechanacimiento="18/03/1970">
            <apellido>Arias</apellido>
            <nombre>Ana</nombre>
            <cargo>Docente</cargo>
            <salario>25.000</salario>
        </empleado>
        <empleado idempleado="1000" fechainicio="04/03/2020" fechanacimiento="03/04/1990">
            <apellido>Garcia</apellido>
            <nombre>Juan</nombre>
            <cargo>Secretario</cargo>
            <salario>30.000</salario>
        </empleado>
    </area>
    <area area="informática">
        <empleado idempleado="1330" fechainicio="14/02/2011" fechanacimiento="17/05/1964">
            <apellido>Ramírez</apellido>
            <nombre>Elena</nombre>
            <cargo>Técnico Laboratorio</cargo>
            <salario>25.000</salario>
        </empleado>
        <empleado idempleado="1285" fechainicio="20/07/2011" fechanacimiento="05/04/1990">
            <apellido>Cortés</apellido>
            <nombre>Ramiro</nombre>
            <cargo>Docente</cargo>
            <salario>45.000</salario>
        </empleado>
        <empleado idempleado="1695" fechainicio="03/04/2020" fechanacimiento="04/03/1990">
            <apellido>Mondragó</apellido>
            <nombre>Unax</nombre>
            <cargo>Docente</cargo>
            <salario>30.000</salario>
        </empleado>
        <empleado idempleado="1900" fechainicio="16/09/2020" fechanacimiento="16/09/1978">
            <apellido>Alba</apellido>
            <nombre>Jaime</nombre>
            <cargo>Docente</cargo>
            <salario>50.000</salario>
        </empleado>
    </area>
</empleados>
